---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.rails-env.name" . }}
data:
  SOLR_BASE_URL: http://{{ template "app.solr.name" . }}:8983/solr
  ZOOKEEPER_ENDPOINT: {{ template "app.zookeeper.name" . }}:2181
  SOLR_URL: http://{{ template "app.solr.name" . }}:8983/solr/{{ .Values.env.configmap.SOLR_CORE }}
  DATABASE_HOST: {{ template "app.mysql.name" . }}
  REDIS_HOST: {{ template "app.redis.name" . }}
  FEDORA_URL: http://{{ template "app.fcrepo.name" . }}:8080/fcrepo/rest
{{- range $key, $value := .Values.env.configmap }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
