---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.web.name" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
      release: {{ .Release.Name }}
      component: web
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        release: {{ .Release.Name }}
        component: web
      annotations:
        checksum/rails-env-cm: {{ include (print $.Template.BasePath "/rails-env-cm.yaml") . | sha256sum }}
        checksum/rails-env-secret: {{ include (print $.Template.BasePath "/rails-env-secret.yaml") . | sha256sum }}
    spec:
      restartPolicy: Always
      {{- if .Values.rails.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.rails.imagePullSecrets }}
      {{- end }}
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: {{ template "app.rails-env.name" . }}-shared
      initContainers:
        - name: check-solr-ready
          image: {{ .Values.rails.image.repository }}:{{ .Values.rails.image.tag }}
          command: ["/bin/bash"]
          args:
            - "-l"
            - "-c"
            - "response=0 && until [ $response == 200 ]; do response=$(curl --write-out %{http_code} --silent --output /dev/null $(echo $SOLR_BASE_URL)/admin/collections?action=LIST); echo Response is $response; sleep 5; done;"
          envFrom:
            - configMapRef:
                name: {{ template "app.rails-env.name" . }}

        # Added this because of listen/inotify errors when trying to access the console
        - name: inotify
          image: {{ .Values.rails.image.repository }}:{{ .Values.rails.image.tag }}
          command: ["/bin/bash"]
          args:
            - "-l"
            - "-c"
            - "sysctl -w fs.inotify.max_user_watches=524288"
          securityContext:
            privileged: true
        # These don't need to be run every time, so really need some checks
        - name: setup
          image: {{ .Values.rails.image.repository }}:{{ .Values.rails.image.tag }}
          command: ["/bin/bash"]
          args:
            - "-l"
            - "-c"
            - "(bundle check || bundle install) && bundle exec rails db:create db:migrate && ruby ./chart/bin/solr-setup.rb && exit 0"
          envFrom:
            - configMapRef:
                name: {{ template "app.rails-env.name" . }}
            - secretRef:
                name: {{ template "app.rails-env.name" . }}
        - name: assets
          image: {{ .Values.rails.image.repository }}:{{ .Values.rails.image.tag }}
          volumeMounts:
            - mountPath: /app/public/assets
              name: shared
              subPath: assets
          command: ["/bin/bash"]
          args:
            - "-l"
            - "-c"
            - "bundle exec rake assets:precompile && exit 0"
          envFrom:
            - configMapRef:
                name: {{ template "app.rails-env.name" . }}
            - secretRef:
                name: {{ template "app.rails-env.name" . }}
        - name: seed
          image: {{ .Values.rails.image.repository }}:{{ .Values.rails.image.tag }}
          command: ["/bin/bash"]
          args:
            - "-l"
            - "-c"
            # db:migrate again because the flexible_metadata migrations haven't been picked up
            - "bundle exec rails db:migrate db:seed && exit 0"
          envFrom:
            - configMapRef:
                name: {{ template "app.rails-env.name" . }}
            - secretRef:
                name: {{ template "app.rails-env.name" . }}
      containers:
        - name: web
          image: {{ .Values.rails.image.repository }}:{{ .Values.rails.image.tag }}
          imagePullPolicy: {{ .Values.rails.imagePullPolicy }}
          # This should be an entrypoint script
          command: ["/bin/bash"]
          args:
            - "-l"
            - "-c"
            - "rm -f /app/tmp/shared/pids/puma.pid && mkdir -p /app/tmp/shared/pids && bundle exec puma -p 80 --pidfile /app/tmp/shared/pids/puma.pid"
          # Use sub-path for individual folders
          volumeMounts:
            - mountPath: /app/tmp/shared
              name: shared
              subPath: shared
            - mountPath: /app/tmp/imports
              name: shared
              subPath: import_path
            - mountPath: /app/tmp/exports
              name: shared
              subPath: export_path
            - mountPath: /app/tmp/derivatives
              name: shared
              subPath: derivatives_path
            - mountPath: /app/tmp/network_files
              name: shared
              subPath: network_files
            - mountPath: /app/tmp/uploads
              name: shared
              subPath: upload_path
            - mountPath: /app/public/uploads
              name: shared
              subPath: uploads
            - mountPath: /app/public/assets
              name: shared
              subPath: assets
            - mountPath: /app/public/branding
              name: shared
              subPath: branding
            - mountPath: /app/public/system
              name: shared
              subPath: system
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 120
          envFrom:
            - configMapRef:
                name: {{ template "app.rails-env.name" . }}
            - secretRef:
                name: {{ template "app.rails-env.name" . }}
